### ISSUE TITLE
Saving a model throws Exception: “This is a deprecated method. Please use saveModel instead.”

### ISSUE THREAD

**Issue by remisharoon** [intel-analytics/analytics-zoo#1980] opened 2020-02-12 07:03 UTC
I am using BigDL + Analytics-Zoo for doing Anomaly detection on time-series data.
When I try to save the model using the .save() method after training,
I am getting the Exception: "This is a deprecated method. Please use saveModel instead."

Generally, deprecations come as a warning, but here it is thrown as an Exception, so I am wondering is this real reason for the Exception? or is there some other reason behind this? If I call 'saveModel' method, it works, but my question is why should the API still keeping a .save() method if it is not supported?

```
model.save(model_path, over_write=True)
.

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-135-b922e545922f> in <module>()
----> 1 model.save(model_path, over_write=True)

/usr/local/lib/python3.6/dist-packages/zoo/pipeline/api/keras/engine/topology.py in save(self, path, over_write)
     31 class KerasNet(ZooKerasLayer):
     32     def save(self, path, over_write=False):
---> 33         raise Exception("This is a deprecated method. Please use saveModel instead.")
     34 
     35     def saveModel(self, modelPath, weightPath=None, over_write=False):

Exception: This is a deprecated method. Please use saveModel instead.
```

**Comment by hkvision** [comment] 2020-02-12 07:55
Hi @remisharoon 

This is somewhat due to our implementation.
Since `KerasNet` eventually inherits BigDL Layer class, and `Layer` has a `save` method, then `KerasNet` will have a `save` method as well. But due to our implementation change, `save` method is out-of-date, and thus in `KerasNet` we just raise an error directly so that users have no possibility to call this method wrongly and get some unexpected behaviors.
As you suggested, it will be better to remove the save method to avoid ambiguity. We would take it into consideration and unify the APIs of BigDL and Analytics Zoo in the future. Thanks so much!

**Comment by helenlly** [comment] 2020-09-16 03:13
@remisharoon  thanks for your question. We will close this issue since no update for a few days. If you have any conerns, free to re-open it. thanks again.

**Closed by helenlly** 2020-09-16 03:13 UTC
