### ISSUE TITLE
 After the model training is over, program will not exit.

### ISSUE THREAD

**Issue by GitEasonXu** [intel-analytics/analytics-zoo#3295] opened 2020-12-28 06:40 UTC
After last epoch was completed, the program will not continue to execute `save model` 、`restore model`

```shell
(pid=71272, ip=10.180.210.67) 
(pid=71272, ip=10.180.210.67)  
(pid=71272, ip=10.180.210.67)     Epoch 00000: Learning rate is 0.0000.
(pid=206254, ip=10.180.210.69) 
(pid=206254, ip=10.180.210.69)  
(pid=206254, ip=10.180.210.69)     Epoch 00000: Learning rate is 0.0000.
(pid=71263, ip=10.180.210.67) 
(pid=71263, ip=10.180.210.67)  
(pid=71263, ip=10.180.210.67)     Epoch 00000: Learning rate is 0.0000.
(pid=206266, ip=10.180.210.69) 
(pid=206266, ip=10.180.210.69)  
(pid=206266, ip=10.180.210.69)     Epoch 00000: Learning rate is 0.0000.
(pid=206072, ip=10.180.210.69) 
(pid=206072, ip=10.180.210.69)  
23/23 [==============================] - 1424s 62s/step - loss: 36.0518 - val_loss: 39.3233
(pid=41193, ip=10.180.210.95)  
(pid=41193, ip=10.180.210.95)  
(pid=41193, ip=10.180.210.95)     Epoch 00000: Learning rate is 0.0000.
(pid=41015, ip=10.180.210.95) 
(pid=41015, ip=10.180.210.95)  
(pid=41015, ip=10.180.210.95)     Epoch 00000: Learning rate is 0.0000.
(pid=41199, ip=10.180.210.95) 
(pid=41199, ip=10.180.210.95)  
(pid=41199, ip=10.180.210.95)     Epoch 00000: Learning rate is 0.0000.
(pid=41021, ip=10.180.210.95) 
(pid=41021, ip=10.180.210.95)  
(pid=41021, ip=10.180.210.95)     Epoch 00000: Learning rate is 0.0000.

```

**Comment by yangw1234** [comment] 2020-12-28 08:06
hi @GitEasonXu , how can we have the code to reproduce this problem?

**Comment by GitEasonXu** [comment] 2020-12-30 08:02
Training VGG model with cifar10 datasets also get same problem. The problem may be related to model complexity.
Hyper-parameters：`Epoch=20`、`Batch_size=320`

**Comment by yangw1234** [comment] 2021-01-04 04:22
hi @GitEasonXu could you try calling `repeat` in the `dataset_creator`, I think it is possible that some shard run out of data and become stuck.

**Comment by GitEasonXu** [comment] 2021-01-05 01:40
I tried it as you suggested, but it didn't solve the problem.
You can use [the code](https://github.com/GitEasonXu/analytics-zoo-test-project/blob/main/tf2-zoo-orca-cifar10-vgg.ipynb) to reproduce the problem.

**Comment by yangw1234** [comment] 2021-01-05 02:03
I'll take a look

**Comment by yangw1234** [comment] 2021-01-05 03:49
@GitEasonXu it seems the problem is caused by saving the model. Can you try removing `est.save` and `est.restore` and see if it still get stuck?

We are currently working on the `save` issue.

**Comment by yangw1234** [comment] 2021-01-05 04:39
#3317 should be able to fix this issue

**Comment by yangw1234** [comment] 2021-01-05 08:16
#3317 merged, please try latest master

**Comment by GitEasonXu** [comment] 2021-01-06 09:25
Hi @yangw1234  thank you!
After reinstalled the latest version of AZ, the problem have been solved.

**Closed** 2021-01-06 09:27 UTC
