### ISSUE TITLE
after pip install, sc = init_nncontext(), it occurs "py4j.protocol.Py4JJavaError"

### ISSUE THREAD

**Issue by linjiaqin** [intel-analytics/analytics-zoo#1611] opened 2019-09-11 07:44 UTC
(zoo) hadoop3@cu11:~$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zoo.common.nncontext import *
Prepending /software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
Adding /software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.9.0-spark_2.4.3-0.6.0-SNAPSHOT-jar-with-dependencies.jar to BIGDL_JARS
Prepending /software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
>>> sc = init_nncontext()
2019-09-11 15:42:28 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/zoo/common/nncontext.py", line 123, in init_nncontext
    init_engine()
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/bigdl/util/common.py", line 418, in init_engine
    callBigDlFunc(bigdl_type, "initEngine")
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/bigdl/util/common.py", line 589, in callBigDlFunc
    raise e
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/bigdl/util/common.py", line 585, in callBigDlFunc
    result = callJavaFunc(api, *args)
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/bigdl/util/common.py", line 634, in callJavaFunc
    result = func(*args)
  File "/usr/local/spark-2.4.3/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/local/spark-2.4.3/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o42.initEngine.
: java.lang.IllegalArgumentException: requirement failed: Engine.init: Can't find executor core number, do you submit with --executor-cores option
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.utils.Engine$.parseExecutorAndCore(Engine.scala:491)
	at com.intel.analytics.bigdl.utils.Engine$.sparkExecutorAndCore(Engine.scala:459)
	at com.intel.analytics.bigdl.utils.Engine$.init(Engine.scala:113)
	at com.intel.analytics.bigdl.python.api.PythonBigDL.initEngine(PythonBigDL.scala:2467)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hkvision** [comment] 2019-09-11 09:32
Hi @linjiaqin The problem is quite strange as you are running in spark local mode and the number of cores should be detected. Are you running the code in your own desktop or other machines?

**Comment by linjiaqin** [comment] 2019-09-11 11:52
> Hi @linjiaqin The problem is quite strange as you are running in spark local mode and the number of cores should be detected. Are you running the code in your own desktop or other machines?

I run it in the spark cluster, dose it matter? But when I run it in my local computer, the same errors happened.

**Comment by hkvision** [comment] 2019-09-12 02:16
> > Hi @linjiaqin The problem is quite strange as you are running in spark local mode and the number of cores should be detected. Are you running the code in your own desktop or other machines?
> 
> hello, @hkvision I run it in the spark cluster, dose it matter? But when I run it in my local computer, the same errors happened.

I have checked our implementation code, you are running in cluster mode but not local mode. Please check your spark master. In the cluster mode, you need to specify the core numbers manually; otherwise we cannot detect the number of cores to use.

**Comment by hkvision** [comment] 2019-09-17 01:52
I'll close this issue first. Feel free to tell us if you have further questions.

**Closed by hkvision** 2019-09-17 01:52 UTC

**Comment by JavadHosseini** [comment] 2021-07-05 06:36
how should we specify the number of cores or other properties?

**Comment by hkvision** [comment] 2021-07-05 07:03
Hi @JavadHosseini 

We have introduced our new API, i.e. init_orca_context and you can specify the cluster mode to be "standalone", and specify cores/memory/num_nodes when calling it. See more details here: https://analytics-zoo.readthedocs.io/en/latest/doc/Orca/Overview/orca.html

**Comment by JavadHosseini** [comment] 2021-07-05 08:11
Thanks, I got new error after applying new api:
`ModuleNotFoundError: No module named 'filelock'`
I installed filelock package but no success.

**Comment by hkvision** [comment] 2021-07-05 08:25
Could you verify if you can use filelock in your python environment? i.e. starting a REPL:
```
python
>>> import filelock
```

**Comment by JavadHosseini** [comment] 2021-07-05 08:51
thank you, It ran successfully. 
there was multiple filelock package on machine.

**Comment by hkvision** [comment] 2021-07-05 09:02
great! glad to hear that!
