### ISSUE TITLE
'NoneType' object has no attribute 'op'

### ISSUE THREAD

**Issue by panzhenfu** [intel-analytics/analytics-zoo#1001] opened 2018-12-21 09:40 UTC
thanks in advance.
when I try to use analytics-zoo to train  Distributed Tensorflow on spark ,I just have a test,but i meet a error like below .
```
def buid_model(x_data,featuresize):
            b = tf.Variable(tf.zeros([1]))
            W = tf.get_variable("W5", shape=[featuresize, 1], dtype=tf.float32, 
            initializer=tf.truncated_normal_initializer(stddev=0.1))
           data = tf.to_float(tf.reshape(x_data, [256, featuresize])) 
            y = tf.matmul(data, W) + b
            return y
```
```
def train(train_data_rdd, val_data_rdd, featuresize):
      dataset = TFDataset.from_rdd(train_data_rdd,
                             names=["features", "label"],
                             shapes=[[featuresize, 1], []],
                             types=[tf.float32, tf.int32],
                             batch_size=256,
                             val_rdd=val_data_rdd
                             )
       features, labels = dataset.tensors
       y_ = tf.to_float(labels)
       y =  buid_model(features,featuresize)
       loss = tf.reduce_mean(tf.square(y_ - y))
       optimizer = TFOptimizer(loss, Adam(1e-3),
                            val_outputs=[y],
                            val_labels=[y_],
                            val_method=Loss(MSECriterion()))
```

I got a error like
`AttributeError                            Traceback (most recent call last)
<ipython-input-35-38a3623d5388> in <module>()
      1 sc = init_nncontext()
----> 2 train(train_data_rdd, val_data_rdd, featuresize)

<ipython-input-34-64a1d397456f> in train(train_data_rdd, val_data_rdd, featuresize)
     69                             val_outputs=[y],
     70                             val_labels=[y_],
---> 71                             val_method=Loss(MSECriterion()))
     72 
     73     optimizer.set_train_summary(TrainSummary(gConfig['log_dir'], "lenet"))

/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip/zoo/pipeline/api/net.py in __init__(self, loss, optim_method, sess, val_outputs, val_labels, val_method)
    402         export_tf(self.sess, self.export_dir,
    403                   inputs=self.inputs,
--> 404                   outputs=grads + outputs)
    405 
    406         variable_names = [v.name for v in variables]

/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip/zoo/util/tf.py in export_tf(sess, folder, inputs, outputs, generate_backward, allow_non_differentiable_input)
     48     """
     49 
---> 50     output_node_names = list({t.op.name for t in outputs})
     51 
     52     graph_def = sess.graph_def

/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip/zoo/util/tf.py in <setcomp>((t,))
     48     """
     49 
---> 50     output_node_names = list({t.op.name for t in outputs})
     51 
     52     graph_def = sess.graph_def

AttributeError: 'NoneType' object has no attribute 'op'`

**Comment by yangw1234** [comment] 2018-12-24 03:12
Hi @panzhenfu , what's the version of your tensorflow. I run your code using tensorflow 1.10.0 (our supported version, see [here](https://analytics-zoo.github.io/master/#ProgrammingGuide/tensorflow/)), it works fine.

**Comment by panzhenfu** [comment] 2018-12-24 05:52
@yangw1234 Thank you for your reply. The version of tensorflow in my system, I have check, was 1.12.0, but  now I have reinstalled tensorflow1.10.0 and the same error still exist. Complete code below

```
import tensorflow as tf
import numpy as np
from zoo import init_nncontext
from zoo.pipeline.api.net import TFOptimizer, TFDataset
from tensorflow.contrib.layers.python.layers import layers as layers_lib

# --------------------------------------
from bigdl.nn.layer import *
from bigdl.nn.criterion import *
from bigdl.optim.optimizer import *

print tf.__version__
        
def buid_model(x_data,featuresize):
    
    data = tf.to_float(tf.reshape(x_data, [256, featuresize])) 
#     y = tf.matmul(data, W) + b
    
    y = layers_lib.legacy_fully_connected(data,1)
    return y
 


def train(train_data_rdd, val_data_rdd, featuresize):
    dataset = TFDataset.from_rdd(train_data_rdd,
                             names=["features", "label"],
                             shapes=[[featuresize, 1], []],
                             types=[tf.float32, tf.int32],
                             batch_size=256,
                             val_rdd=val_data_rdd
                             )

    # construct the model from TFDataset
    features, labels = dataset.tensors
    
    y_ = tf.to_float(labels)
    
    y =  buid_model(features,featuresize)
    
    loss = tf.reduce_mean(tf.square(y_ - y))

    # create a optimizer
    optimizer = TFOptimizer(loss, Adam(1e-3),
                            val_outputs=[y],
                            val_labels=[y_],
                            val_method=Loss(MSECriterion()))
    
    optimizer.set_train_summary(TrainSummary("./log", "lenet"))
    optimizer.set_val_summary(ValidationSummary("./log", "lenet"))
    # kick off training
    optimizer.optimize(end_trigger=MaxEpoch(100))

    saver = tf.train.Saver()
    saver.save(optimizer.sess, "./lenet/")
    
sc = init_nncontext()

# 使用 NumPy 生成假数据(phony data), 总共 100 个点.
x_data = np.float32(np.random.rand(512, 100)) # 随机输入
y_data = np.dot(np.float32(np.random.rand(100, 512)), x_data) + 0.300
val_x = x_data + 0.01
val_y = y_data + 0.01

image_rdd = sc.parallelize(x_data)
labels_rdd = sc.parallelize(y_data)
rdd = image_rdd.zip(labels_rdd) \
    .map(lambda rec_tuple: [np.array(rec_tuple[0]),
                                    np.array(rec_tuple[1])])

val_image_rdd = sc.parallelize(val_x)
val_labels_rdd = sc.parallelize(val_y)
val_rdd = val_image_rdd.zip(val_labels_rdd) \
    .map(lambda rec_tuple: [np.array(rec_tuple[0]),
                                    np.array(rec_tuple[1])])

train(rdd, val_rdd, 100) 
```
and the output 
```
1.10.0
creating: createAdam
creating: createMSECriterion
creating: createLoss
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-34b5f917890f> in <module>()
     72                                     np.array(rec_tuple[1])])
     73 
---> 74 train(rdd, val_rdd, 100)

<ipython-input-7-34b5f917890f> in train(train_data_rdd, val_data_rdd, featuresize)
     44                             val_outputs=[y],
     45                             val_labels=[y_],
---> 46                             val_method=Loss(MSECriterion()))
     47 
     48     optimizer.set_train_summary(TrainSummary("./log", "lenet"))

/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip/zoo/pipeline/api/net.py in __init__(self, loss, optim_method, sess, val_outputs, val_labels, val_method)
    402         export_tf(self.sess, self.export_dir,
    403                   inputs=self.inputs,
--> 404                   outputs=grads + outputs)
    405 
    406         variable_names = [v.name for v in variables]

/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip/zoo/util/tf.py in export_tf(sess, folder, inputs, outputs, generate_backward, allow_non_differentiable_input)
     48     """
     49 
---> 50     output_node_names = list({t.op.name for t in outputs})
     51 
     52     graph_def = sess.graph_def

/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip/zoo/util/tf.py in <setcomp>((t,))
     48     """
     49 
---> 50     output_node_names = list({t.op.name for t in outputs})
     51 
     52     graph_def = sess.graph_def

AttributeError: 'NoneType' object has no attribute 'op'
```

**Comment by yangw1234** [comment] 2018-12-25 02:43
@panzhenfu I still cannot reproduce your error. What's the version of your analytics-zoo.
And by the way, there are some errors in your code.

 1. the `y_data`'s first dimension should be the same as `x_data`, you should use switch the two arguments in your np.dot. 

2. in build_model, you should not hard code batchsize in reshape, as the actual tensor feed to tensorflow in each thread is actual batchsize/num_of_total_spark_core, you should use `tf.reshape(x_data, [-1, featuresize])` instead. 

3. you should specify the right shape and types in TFDataset.from_rdd

```python
    dataset = TFDataset.from_rdd(train_data_rdd,
                                 names=["features", "label"],
                                 shapes=[[featuresize], [featuresize]],
                                 types=[tf.float32, tf.intfloat32],
                                 batch_size=256,
                                 val_rdd=val_data_rdd
                                 )
``` 
After fixing these problems, I run you code successfully on the current master.

**Comment by yangw1234** [comment] 2018-12-25 02:49
@panzhenfu it seems that in your tensorflow some variable are not differentiable. You can print tf.trainable_variables() for debugging.

**Comment by panzhenfu** [comment] 2018-12-27 02:40
I really appreciate your kindness and patience. and I have fixed the bugs you mentioned and train my data and model with tensorflow purely that can work fine. The package, I used, is **analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip** ,I still got the same error.
```
import tensorflow as tf
import numpy as np
from zoo import init_nncontext
from zoo.pipeline.api.net import TFOptimizer, TFDataset
from tensorflow.contrib.layers.python.layers import layers as layers_lib

# --------------------------------------
from bigdl.nn.layer import *
from bigdl.nn.criterion import *
from bigdl.optim.optimizer import *

print tf.__version__


sc = init_nncontext()

# 使用 NumPy 生成假数据(phony data), 总共 100 个点.
x_data = np.float32(np.random.rand(512, 100)) # 随机输入
y_data = np.dot(x_data, np.float32(np.random.rand(100, 1))) + 0.300
val_x = x_data + 0.01
val_y = y_data + 0.01


def buid_model(x_data,featuresize):
    
    data = tf.reshape(x_data, [-1, featuresize]) 
    y = layers_lib.legacy_fully_connected(data,1)
    return y
 


def trainAZ(x_data, y_data,val_x,val_y,featuresize,bathsize):
    
    im_rdd = sc.parallelize(x_data)
    labels_rdd = sc.parallelize(y_data)
    train_rdd = im_rdd.zip(labels_rdd) \
        .map(lambda rec_tuple: [np.array(rec_tuple[0]),
                                        np.array(rec_tuple[1])])

    val_rdd = sc.parallelize(val_x)
    val_labels_rdd = sc.parallelize(val_y)
    val_rdd = val_rdd.zip(val_labels_rdd) \
        .map(lambda rec_tuple: [np.array(rec_tuple[0]),
                                        np.array(rec_tuple[1])])
    
    dataset = TFDataset.from_rdd(train_rdd,
                             names=["features", "label"],
                             shapes=[[featuresize], [1]],
                             types=[tf.float32, tf.float32],
                             batch_size=bathsize,
                             val_rdd=val_rdd
                             )

    # construct the model from TFDataset
    features, labels = dataset.tensors
    
    y =  buid_model(features,featuresize)
    
    loss = tf.reduce_mean(tf.square(labels - y))

    # create a optimizer
    optimizer = TFOptimizer(loss, Adam(1e-3),
                            val_outputs=[y],
                            val_labels=[labels],
                            val_method=Loss(MSECriterion()))
    
#     optimizer.set_train_summary(TrainSummary("./log", "lenet"))
#     optimizer.set_val_summary(ValidationSummary("./log", "lenet"))
#     # kick off training
    optimizer.optimize(end_trigger=MaxEpoch(100))

#     saver = tf.train.Saver()
#     saver.save(optimizer.sess, "./lenet/")


def tensorTrain(x_data,y_data,val_x,val_y,featuresize,bathsize):
    X_placeholder = tf.placeholder(shape=[None,featuresize],dtype=tf.float32)
    label_placeholder = tf.placeholder(shape=[None,1],dtype=tf.float32)

    y =  buid_model(X_placeholder,featuresize)

    loss = tf.reduce_mean(tf.square(label_placeholder - y))
    optimizer = tf.train.GradientDescentOptimizer(0.002)
    train = optimizer.minimize(loss)

    # 初始化变量
    init = tf.global_variables_initializer()

    sess = tf.Session()
    sess.run(init)

    for step in xrange(0, 10001):
        rand_index1 = np.random.choice(512,size=bathsize)
        rand_x1 = x_data[rand_index1,:]
        rand_y1 = y_data[rand_index1,:]
        sess.run(train, feed_dict={X_placeholder: rand_x1, label_placeholder: rand_y1})

        if step % 20 == 0:
            print step, sess.run(loss, feed_dict={X_placeholder: val_x, label_placeholder: val_y})
# tensorTrain(x_data,y_data,val_x,val_y,100,256)
trainAZ(x_data,y_data,val_x,val_y,100,256)
```
```
1.10.0
creating: createAdam
creating: createMSECriterion
creating: createLoss
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-33eda8524159> in <module>()
    101             print step, sess.run(loss, feed_dict={X_placeholder: val_x, label_placeholder: val_y})
    102 # tensorTrain(x_data,y_data,val_x,val_y,100,256)
--> 103 trainAZ(x_data,y_data,val_x,val_y,100,256)
    104 # train(rdd, val_rdd, 100)

<ipython-input-17-33eda8524159> in trainAZ(x_data, y_data, val_x, val_y, featuresize, bathsize)
     61                             val_outputs=[y],
     62                             val_labels=[labels],
---> 63                             val_method=Loss(MSECriterion()))
     64 
     65 #     optimizer.set_train_summary(TrainSummary("./log", "lenet"))

/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip/zoo/pipeline/api/net.py in __init__(self, loss, optim_method, sess, val_outputs, val_labels, val_method)
    402         export_tf(self.sess, self.export_dir,
    403                   inputs=self.inputs,
--> 404                   outputs=grads + outputs)
    405 
    406         variable_names = [v.name for v in variables]

/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip/zoo/util/tf.py in export_tf(sess, folder, inputs, outputs, generate_backward, allow_non_differentiable_input)
     48     """
     49 
---> 50     output_node_names = list({t.op.name for t in outputs})
     51 
     52     graph_def = sess.graph_def

/home/anaconda2/envs/tensorflow/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.7.1-spark_2.2.0-0.3.0-python-api.zip/zoo/util/tf.py in <setcomp>((t,))
     48     """
     49 
---> 50     output_node_names = list({t.op.name for t in outputs})
     51 
     52     graph_def = sess.graph_def

AttributeError: 'NoneType' object has no attribute 'op'
```
please help me.

**Comment by yangw1234** [comment] 2020-09-21 02:28
This has been fixed. Closing it.

**Closed by yangw1234** 2020-09-21 02:28 UTC

**Comment by yangw1234** [comment] 2022-09-21 02:43
> hello, how do you fix your problem？ this error also come up when I take the derivative with tensorflow

@thevelvetunderground thank you for your comments. 

Are you using analytics zoo code? If you are using analytics zoo code, would you mind giving us a code snippet so that we can reproduce the problem on our side.

If you are using tensorflow directly, my guess is that one of the your variables you are taking derivatives of are not differentiable, so that the derivative returned by tensorflow is a None.
