### ISSUE TITLE
Run the Object Detection problem (Messi) on the distributed cluster

### ISSUE THREAD

**Issue by beta21s** [intel-analytics/analytics-zoo#3494] opened 2021-02-15 04:21 UTC
Hi everybody,
I installed spark to run the object detection problem on a single machine, it ran successfully but when I installed on the cluster I could not train

I install the machine as follows
```
master: 
hostname: at-master, IP: 10.10.100.117
cluster:
hostname: at-clustera, IP: 10.10.100.119
hostname: at-clusterb, IP: 10.10.100.123
```
```
spark-submit \
    --master spark://10.10.100.117:7077 \
    --deploy-mode cluster \
    --driver-memory 16g \
    --executor-memory 16g \
    --total-executor-cores 2 \
    --conf "spark.serializer=org.apache.spark.serializer.JavaSerializer" \
    --class com.intel.analytics.zoo.examples.objectdetection.finetune.ssd.Train \
    hdfs://10.10.100.117:9000/data/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-jar-with-dependencies.jar \
    --resolution 300 \
    --model hdfs://10.10.100.117:9000/data/analytics-zoo_ssd-vgg16-300x300_COCO_0.1.0.model \
    --class /home/at/Desktop/xhn/classname.txt \
    -f hdfs://10.10.100.117:9000/data/seq/train \
    -v hdfs://10.10.100.117:9000/data/seq/test \
    -e 2 -b 4 \
    --modelDir hdfs://10.10.100.117:9000/data/model \
    -l 0.0001 --learningRateDecay 0.0005
```
Results from terminal
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/usr/local/lib/python3.6/dist-packages/pyspark/jars/spark-unsafe_2.11-2.4.3.jar) to method java.nio.Bits.unaligned()
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.NativeCodeLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/02/15 11:09:29 INFO SecurityManager: Changing view acls to: at
21/02/15 11:09:29 INFO SecurityManager: Changing modify acls to: at
21/02/15 11:09:29 INFO SecurityManager: Changing view acls groups to: 
21/02/15 11:09:29 INFO SecurityManager: Changing modify acls groups to: 
21/02/15 11:09:29 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(at); groups with view permissions: Set(); users  with modify permissions: Set(at); groups with modify permissions: Set()
21/02/15 11:09:30 INFO Utils: Successfully started service 'driverClient' on port 33555.
21/02/15 11:09:30 INFO TransportClientFactory: Successfully created connection to /10.10.100.117:7077 after 17 ms (0 ms spent in bootstraps)
21/02/15 11:09:30 INFO ClientEndpoint: Driver successfully submitted as driver-20210215110930-0000
21/02/15 11:09:30 INFO ClientEndpoint: ... waiting before polling master for driver state
21/02/15 11:09:35 INFO ClientEndpoint: ... polling master for driver state
21/02/15 11:09:35 INFO ClientEndpoint: State of driver-20210215110930-0000 is RUNNING
21/02/15 11:09:35 INFO ClientEndpoint: Driver running on 127.0.0.1:42117 (worker-20210215110154-127.0.0.1-42117)
21/02/15 11:09:35 INFO ShutdownHookManager: Shutdown hook called
21/02/15 11:09:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-82a0ff3b-8e8a-44ac-8afc-1f159be4a197

```
stderr log page for app-20210215110933-0001/7 
```
Spark Executor Command: "/usr/lib/jvm/java-11-openjdk-amd64/bin/java" "-cp" "/opt/spark-2.4.3/conf/:/opt/spark-2.4.3/jars/*" "-Xmx16384M" "-Dspark.driver.port=45679" "-Dspark.rpc.askTimeout=10s" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@localhost:45679" "--executor-id" "7" "--hostname" "10.10.100.119" "--cores" "1" "--app-id" "app-20210215110933-0001" "--worker-url" "spark://Worker@10.10.100.119:33245"
========================================

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/02/15 11:09:44 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 27016@at-clustera
21/02/15 11:09:44 INFO SignalUtils: Registered signal handler for TERM
21/02/15 11:09:44 INFO SignalUtils: Registered signal handler for HUP
21/02/15 11:09:44 INFO SignalUtils: Registered signal handler for INT
21/02/15 11:09:45 WARN Utils: Your hostname, at-clustera resolves to a loopback address: 127.0.1.1; using 10.10.100.119 instead (on interface enp0s3)
21/02/15 11:09:45 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark-2.4.3/jars/spark-unsafe_2.11-2.4.3.jar) to method java.nio.Bits.unaligned()
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21/02/15 11:09:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/02/15 11:09:45 INFO SecurityManager: Changing view acls to: at,root
21/02/15 11:09:45 INFO SecurityManager: Changing modify acls to: at,root
21/02/15 11:09:45 INFO SecurityManager: Changing view acls groups to: 
21/02/15 11:09:45 INFO SecurityManager: Changing modify acls groups to: 
21/02/15 11:09:45 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(at, root); groups with view permissions: Set(); users  with modify permissions: Set(at, root); groups with modify permissions: Set()
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1713)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:64)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:188)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:281)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:201)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:65)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:64)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	... 4 more
Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:45679
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:245)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:198)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:194)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:190)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:45679
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
Caused by: java.net.ConnectException: Connection refused
	... 11 more
```

I don't know how to handle it, I hope everyone will help me.
Thank you very much

**Comment by qiyuangong** [comment] 2021-02-16 13:33
Hi @beta21s 
According to your error log, it seems like an Spark configuration problem.
`Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:45679` means that Spark master cannot connect to worker node.

Pls check your spark configurations, e.g., set `SPARK_LOCAL_IP`.

**Comment by beta21s** [comment] 2021-02-18 01:28
Thank you for your help

```SPARK_LOCAL_IP``` ```spark-env.sh``` is only installed at master or all machines in the cluster.

For example: 
```spark-env.sh```  in ```at-master``` add line ```export SPARK_LOCAL_IP=at-master``` Is that true?

Thank you very much

**Comment by qiyuangong** [comment] 2021-02-18 02:41
> Thank you for your help
> 
> `SPARK_LOCAL_IP` `spark-env.sh` is only installed at master or all machines in the cluster.
> 
> For example:
> `spark-env.sh` in `at-master` add line `export SPARK_LOCAL_IP=at-master` Is that true?
> 
> Thank you very much

Yes. Please ensure they (master and workers) can find each other.
Also check `/etc/hosts` and `slaves` files when checking configurations.

After reset configuration, you can verify Spark cluster with Spark examples (https://spark.apache.org/docs/2.4.3/submitting-applications.html#master-urls)

**Comment by qiyuangong** [comment] 2021-11-26 07:21
Hi @beta21s 
Any update to this issue?
Can we close this issue?

**Comment by helenlly** [comment] 2021-12-07 02:55
close due to no response for a long time.

**Closed** 2021-12-07 02:54 UTC
Labels: user issue
