### ISSUE TITLE
Files in the root directory

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/analytics-zoo#3733] opened 2021-04-07 03:51 UTC
- pom.xml
- make-dist.sh
- pyproject.toml

Why are they in the root directory?

**Comment by Le-Zheng** [comment] 2021-04-07 05:54
Initially, it might be intended to manage several modules. Actually, only `/zoo`  programs require maven. Shall we move "pom.xml" and "make-dist.sh" under `/zoo`? The released artifacts will also be changed.

**Comment by jason-dai** [comment] 2021-04-07 06:17
> Initially, it might be intended to manage several modules. Actually, only `/zoo` programs require maven. Shall we move "pom.xml" and "make-dist.sh" under `/zoo`? The released artifacts will also be changed.

Yes, let's move these under `/zoo`

**Comment by helenlly** [comment] 2021-04-08 03:13
tested and confirmed , pyproject.toml is required to be in root when building readthedocs.   
checked other projects using readthedocs, e.g.  pytorch-lightning ...  pyproject.toml is in their root too.

**Comment by Le-Zheng** [comment] 2021-04-26 08:23
Fixed in https://github.com/intel-analytics/analytics-zoo/pull/3736

**Closed by Le-Zheng** 2021-04-26 08:23 UTC
